# Generated by Django 2.2.2 on 2019-07-02 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100, null=True, verbose_name='book')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=100, verbose_name='teacher name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_usn',
            field=models.CharField(max_length=11, null=True, verbose_name='USN'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, choices=[('fafl', 'finite automata and formal languages'), ('mc', 'microcontroller'), ('ada', 'analysis and design of algorithm')], max_length=40, null=True, verbose_name='sub'),
        ),
        migrations.AddField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100, null=True, verbose_name='library')),
                ('books', models.ManyToManyField(null=True, to='home.book')),
            ],
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=30, null=True, verbose_name='college')),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student')),
            ],
        ),
    ]
